상관분석 (and 편상관분석)
=======================================================

의미 : 선형적 상관관계의 정도를 보는 것

### 실습1 : 모수적 상관분석

1) 허리둘레와 BMI의 산점도를 그린다.

```{r}
setwd("~/SparkleShare/learnR/Rstar/보건의학통계/lesson06")
data <- read.csv("6_correlation_and_regression.csv", header=T)
head(data)
```

```{r fig.width=7, fig.height=6}
# plot
plot(data)
plot(BMI~waistline, data=data)

# corrplot
data.cor <- cor(data)
library(corrplot)
corrplot(data.cor, method='shade', shade.col=NA, tl.col='black', tl.srt=45, order='hclust')
```

2) 허리둘레와 BMI의 상관관계를 분석한다. 

```{r}
data.cor['waistline','BMI']
cor.test(data$waistline, data$BMI)
```

3) 체중의 영향을 고려하여 허리둘레와 BMI의 편상관계수를 구한다. 

```{r}
#install.packages('ppcor')
library('ppcor')
pcor.test(data$waistline, data$BMI, data$weight)
```

### 실습2 : 비모수 상관분석
```{r}
data2 <- read.csv("6_spearman.csv", header=T)
head(data2)

cor.test(data2$Age, data2$SBP, method= "spearman")
cor.test(data2$Age, data2$SBP, method= "kendall")
```


### 실습3 : 단순회귀분석
```{r}
data.lm <- lm(data$BMI ~ data$waistline)
summary(data.lm)
```

```{r fig.width=7, fig.height=6}
plot(data$BMI ~ data$waistline)
abline(data.lm)
```


